import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "@/app/StoreProvider";
import "../styles/globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <h2>
            <Link href="/">
              IT Company Employee
            </Link>
          </h2>
        </header>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
